// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_command.proto

#ifndef PROTOBUF_robot_5fcommand_2eproto__INCLUDED
#define PROTOBUF_robot_5fcommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_robot_5fcommand_2eproto();
void protobuf_AssignDesc_robot_5fcommand_2eproto();
void protobuf_ShutdownFile_robot_5fcommand_2eproto();

class RobotCommand;

// ===================================================================

class RobotCommand : public ::google::protobuf::Message {
 public:
  RobotCommand();
  virtual ~RobotCommand();

  RobotCommand(const RobotCommand& from);

  inline RobotCommand& operator=(const RobotCommand& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RobotCommand& default_instance();

  void Swap(RobotCommand* other);

  // implements Message ----------------------------------------------

  RobotCommand* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RobotCommand& from);
  void MergeFrom(const RobotCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 frame_number = 1;
  inline bool has_frame_number() const;
  inline void clear_frame_number();
  static const int kFrameNumberFieldNumber = 1;
  inline ::google::protobuf::uint32 frame_number() const;
  inline void set_frame_number(::google::protobuf::uint32 value);

  // required double t_capture = 2;
  inline bool has_t_capture() const;
  inline void clear_t_capture();
  static const int kTCaptureFieldNumber = 2;
  inline double t_capture() const;
  inline void set_t_capture(double value);

  // required double t_sent = 3;
  inline bool has_t_sent() const;
  inline void clear_t_sent();
  static const int kTSentFieldNumber = 3;
  inline double t_sent() const;
  inline void set_t_sent(double value);

  // required uint32 camera_id = 4;
  inline bool has_camera_id() const;
  inline void clear_camera_id();
  static const int kCameraIdFieldNumber = 4;
  inline ::google::protobuf::uint32 camera_id() const;
  inline void set_camera_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:RobotCommand)
 private:
  inline void set_has_frame_number();
  inline void clear_has_frame_number();
  inline void set_has_t_capture();
  inline void clear_has_t_capture();
  inline void set_has_t_sent();
  inline void clear_has_t_sent();
  inline void set_has_camera_id();
  inline void clear_has_camera_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double t_capture_;
  ::google::protobuf::uint32 frame_number_;
  ::google::protobuf::uint32 camera_id_;
  double t_sent_;
  friend void  protobuf_AddDesc_robot_5fcommand_2eproto();
  friend void protobuf_AssignDesc_robot_5fcommand_2eproto();
  friend void protobuf_ShutdownFile_robot_5fcommand_2eproto();

  void InitAsDefaultInstance();
  static RobotCommand* default_instance_;
};
// ===================================================================


// ===================================================================

// RobotCommand

// required uint32 frame_number = 1;
inline bool RobotCommand::has_frame_number() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RobotCommand::set_has_frame_number() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RobotCommand::clear_has_frame_number() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RobotCommand::clear_frame_number() {
  frame_number_ = 0u;
  clear_has_frame_number();
}
inline ::google::protobuf::uint32 RobotCommand::frame_number() const {
  // @@protoc_insertion_point(field_get:RobotCommand.frame_number)
  return frame_number_;
}
inline void RobotCommand::set_frame_number(::google::protobuf::uint32 value) {
  set_has_frame_number();
  frame_number_ = value;
  // @@protoc_insertion_point(field_set:RobotCommand.frame_number)
}

// required double t_capture = 2;
inline bool RobotCommand::has_t_capture() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RobotCommand::set_has_t_capture() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RobotCommand::clear_has_t_capture() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RobotCommand::clear_t_capture() {
  t_capture_ = 0;
  clear_has_t_capture();
}
inline double RobotCommand::t_capture() const {
  // @@protoc_insertion_point(field_get:RobotCommand.t_capture)
  return t_capture_;
}
inline void RobotCommand::set_t_capture(double value) {
  set_has_t_capture();
  t_capture_ = value;
  // @@protoc_insertion_point(field_set:RobotCommand.t_capture)
}

// required double t_sent = 3;
inline bool RobotCommand::has_t_sent() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RobotCommand::set_has_t_sent() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RobotCommand::clear_has_t_sent() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RobotCommand::clear_t_sent() {
  t_sent_ = 0;
  clear_has_t_sent();
}
inline double RobotCommand::t_sent() const {
  // @@protoc_insertion_point(field_get:RobotCommand.t_sent)
  return t_sent_;
}
inline void RobotCommand::set_t_sent(double value) {
  set_has_t_sent();
  t_sent_ = value;
  // @@protoc_insertion_point(field_set:RobotCommand.t_sent)
}

// required uint32 camera_id = 4;
inline bool RobotCommand::has_camera_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RobotCommand::set_has_camera_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RobotCommand::clear_has_camera_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RobotCommand::clear_camera_id() {
  camera_id_ = 0u;
  clear_has_camera_id();
}
inline ::google::protobuf::uint32 RobotCommand::camera_id() const {
  // @@protoc_insertion_point(field_get:RobotCommand.camera_id)
  return camera_id_;
}
inline void RobotCommand::set_camera_id(::google::protobuf::uint32 value) {
  set_has_camera_id();
  camera_id_ = value;
  // @@protoc_insertion_point(field_set:RobotCommand.camera_id)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_robot_5fcommand_2eproto__INCLUDED
