# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_plot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_plot.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64\x61ta_plot.proto\".\n\x08point_2D\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x02(\x02\x12\t\n\x01y\x18\x03 \x02(\x02\"6\n\x0b\x66unction_2D\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x06points\x18\x02 \x03(\x0b\x32\t.point_2D\"1\n\x10\x66unction_wrapper\x12\x1d\n\x07\x66uncArr\x18\x01 \x03(\x0b\x32\x0c.function_2D\"*\n\nraw_points\x12\x1c\n\tallPoints\x18\x01 \x03(\x0b\x32\t.point_2D\"$\n\tdata_flow\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x03(\x02\"-\n\tdata_gram\x12 \n\x0c\x64\x61ta_package\x18\x01 \x03(\x0b\x32\n.data_flow')
)




_POINT_2D = _descriptor.Descriptor(
  name='point_2D',
  full_name='point_2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='point_2D.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='point_2D.x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='point_2D.y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=65,
)


_FUNCTION_2D = _descriptor.Descriptor(
  name='function_2D',
  full_name='function_2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='function_2D.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='function_2D.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=121,
)


_FUNCTION_WRAPPER = _descriptor.Descriptor(
  name='function_wrapper',
  full_name='function_wrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='funcArr', full_name='function_wrapper.funcArr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=172,
)


_RAW_POINTS = _descriptor.Descriptor(
  name='raw_points',
  full_name='raw_points',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allPoints', full_name='raw_points.allPoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=216,
)


_DATA_FLOW = _descriptor.Descriptor(
  name='data_flow',
  full_name='data_flow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='data_flow.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='data_flow.y', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=254,
)


_DATA_GRAM = _descriptor.Descriptor(
  name='data_gram',
  full_name='data_gram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_package', full_name='data_gram.data_package', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=301,
)

_FUNCTION_2D.fields_by_name['points'].message_type = _POINT_2D
_FUNCTION_WRAPPER.fields_by_name['funcArr'].message_type = _FUNCTION_2D
_RAW_POINTS.fields_by_name['allPoints'].message_type = _POINT_2D
_DATA_GRAM.fields_by_name['data_package'].message_type = _DATA_FLOW
DESCRIPTOR.message_types_by_name['point_2D'] = _POINT_2D
DESCRIPTOR.message_types_by_name['function_2D'] = _FUNCTION_2D
DESCRIPTOR.message_types_by_name['function_wrapper'] = _FUNCTION_WRAPPER
DESCRIPTOR.message_types_by_name['raw_points'] = _RAW_POINTS
DESCRIPTOR.message_types_by_name['data_flow'] = _DATA_FLOW
DESCRIPTOR.message_types_by_name['data_gram'] = _DATA_GRAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

point_2D = _reflection.GeneratedProtocolMessageType('point_2D', (_message.Message,), {
  'DESCRIPTOR' : _POINT_2D,
  '__module__' : 'data_plot_pb2'
  # @@protoc_insertion_point(class_scope:point_2D)
  })
_sym_db.RegisterMessage(point_2D)

function_2D = _reflection.GeneratedProtocolMessageType('function_2D', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTION_2D,
  '__module__' : 'data_plot_pb2'
  # @@protoc_insertion_point(class_scope:function_2D)
  })
_sym_db.RegisterMessage(function_2D)

function_wrapper = _reflection.GeneratedProtocolMessageType('function_wrapper', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTION_WRAPPER,
  '__module__' : 'data_plot_pb2'
  # @@protoc_insertion_point(class_scope:function_wrapper)
  })
_sym_db.RegisterMessage(function_wrapper)

raw_points = _reflection.GeneratedProtocolMessageType('raw_points', (_message.Message,), {
  'DESCRIPTOR' : _RAW_POINTS,
  '__module__' : 'data_plot_pb2'
  # @@protoc_insertion_point(class_scope:raw_points)
  })
_sym_db.RegisterMessage(raw_points)

data_flow = _reflection.GeneratedProtocolMessageType('data_flow', (_message.Message,), {
  'DESCRIPTOR' : _DATA_FLOW,
  '__module__' : 'data_plot_pb2'
  # @@protoc_insertion_point(class_scope:data_flow)
  })
_sym_db.RegisterMessage(data_flow)

data_gram = _reflection.GeneratedProtocolMessageType('data_gram', (_message.Message,), {
  'DESCRIPTOR' : _DATA_GRAM,
  '__module__' : 'data_plot_pb2'
  # @@protoc_insertion_point(class_scope:data_gram)
  })
_sym_db.RegisterMessage(data_gram)


# @@protoc_insertion_point(module_scope)
